#!/usr/bin/env python3
"""Synthetic and end-to-end tests for the retained-power normalization audit.

The suite covers the normalization identities of the frozen source-ensemble
contract (aligned columns, exact cancellation, global and uniform area scale
invariance, mesh splitting, the weighted-Jensen bound, the independent-phase
expectation and whole-sheet scaling), malformed-input rejection, and a
end-to-end fixture in which artifacts generated by the frozen implementation
are audited by the independent recomputation.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import shutil
import subprocess
import sys
import tempfile
import unittest
from datetime import datetime, timezone
from pathlib import Path

import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[1]
for location in (PROJECT_ROOT, PROJECT_ROOT / "scripts"):
    if str(location) not in sys.path:
        sys.path.insert(0, str(location))

from anatomical.hippunfold_ensembles import (  # noqa: E402
    build_source_supports,
    deterministic_phase,
    oriented_intrinsic_coordinates,
    patch_coherence_metrics,
    phase_locked_metrics,
    random_correlated_phases,
    referenced_leadfield,
    standardized_nuisance,
    support_identifier,
)
from anatomical.retained_power_audit import (  # noqa: E402
    PROTOCOL,
    AuditError,
    coherent_patch_index,
    independent_phase_power,
    load_fixed_leadfield,
    load_metadata,
    resolve_declared_input,
    retained_power,
    support_weights,
    synthetic_checks_passed,
    synthetic_identity_checks,
    unit_phase_from_angles,
    whole_sheet_power,
)


AUDIT_SCRIPT = PROJECT_ROOT / "scripts" / "audit_retained_power_normalization.py"
ADDENDUM = "hcp_hippunfold_retained_power_normalization_addendum_v1.md"

FIXTURE_SUBJECT = "123456"
FIXTURE_SENSORS = 9
FIXTURE_RANDOM_REPLICATES = 2
FIXTURE_RANDOM_FEATURES = 32
FIXTURE_SUPPORT = {
    "hemisphere_families": ["left", "right", "bilateral"],
    "focal_locations": ["anterior", "middle", "posterior"],
    "focal_extents": [0.05, 0.10, 0.25, 0.50],
    "include_whole_extent": True,
    "endpoint_decile": 0.10,
    "minimum_endpoint_separation_m": 0.015,
    "maximum_fraction_overshoot_patch_multiplier": 1.000001,
}
FIXTURE_RANDOM_SUPPORTS = [
    {"hemisphere": "left", "location": "whole", "extent": 1.0},
    {"hemisphere": "right", "location": "whole", "extent": 1.0},
    {"hemisphere": "bilateral", "location": "whole", "extent": 1.0},
    {"hemisphere": "bilateral", "location": "anterior", "extent": 0.25},
    {"hemisphere": "bilateral", "location": "middle", "extent": 0.25},
    {"hemisphere": "bilateral", "location": "posterior", "extent": 0.25},
]


def _fixture_config() -> dict[str, object]:
    return {
        "schema_version": 1,
        "protocol": PROTOCOL,
        "support": dict(FIXTURE_SUPPORT),
        "deterministic_phase": {"wave_cycles": [0.25, 0.50, 1.0, 2.0]},
        "patch_coherence": {
            "intrinsic_bin_widths": [0.05, 0.10, 0.25, 0.50, 1.0],
            "hemispheres_independent": True,
        },
        "random_phase": {
            "intrinsic_correlation_lengths": [0.05, 0.10, 0.25, 0.50],
            "replicates": FIXTURE_RANDOM_REPLICATES,
            "random_fourier_features": FIXTURE_RANDOM_FEATURES,
            "marginal_phase_standard_deviation_rad": math.pi,
            "master_seed": 20260830,
            "supports": [dict(row) for row in FIXTURE_RANDOM_SUPPORTS],
        },
        "expected_sensors": FIXTURE_SENSORS,
        "maximum_numerical_bound_error": 1e-10,
        "standardized_noise_fraction": 0.1,
    }


def _fixture_geometry(points: int = 48) -> dict[str, np.ndarray]:
    half = points // 2
    ap = np.linspace(0.0, 1.0, half)
    pd = np.mod(np.arange(half), 5) / 4.0
    left = np.column_stack((-0.02 * np.ones(half), -0.03 + 0.06 * ap, 0.01 * pd))
    right = left.copy()
    right[:, 0] *= -1.0
    return {
        "positions_m": np.vstack((left, right)),
        "longitudinal_coordinate": np.concatenate((ap, ap)),
        "proximal_distal_coordinate": np.concatenate((pd, pd)),
        "hemisphere_code": np.concatenate(
            (-np.ones(half, dtype=np.int8), np.ones(half, dtype=np.int8))
        ),
        "area_weights_m2": np.linspace(0.8, 1.2, points),
        "directions": np.tile(np.array([0.0, 0.0, 1.0]), (points, 1)),
    }


def _write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    fields: list[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    with path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields, extrasaction="raise")
        writer.writeheader()
        writer.writerows(rows)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _support_fields(support) -> dict[str, object]:
    return {
        "support_id": support.identifier,
        "hemisphere": support.hemisphere,
        "location": support.location,
        "target_extent": support.target_extent,
        "source_count": len(support.indices),
        "full_sheet_area_fraction": support.full_sheet_area_fraction,
        "realized_extent_within_selected_hemispheres": (
            support.realized_extent_within_selected_hemispheres
        ),
        "realized_extent_by_hemisphere_json": json.dumps(
            support.realized_extent_by_hemisphere, sort_keys=True
        ),
    }


def _regimes(config: dict[str, object]) -> list[tuple[str, float]]:
    cycles = list(dict(config["deterministic_phase"])["wave_cycles"])  # type: ignore[index]
    return [("zero_phase", 0.0)] + [
        (f"wave_{float(cycle):g}_cycles", float(cycle)) for cycle in cycles
    ]


def generate_fixture(root: Path) -> dict[str, Path]:
    """Write a miniature but structurally faithful source-ensemble subject tree."""

    config = _fixture_config()
    geometry = _fixture_geometry()
    forward_root = root / "forward"
    result_root = root / "results"
    subject_forward = forward_root / FIXTURE_SUBJECT
    subject_results = result_root / FIXTURE_SUBJECT
    subject_forward.mkdir(parents=True)
    subject_results.mkdir(parents=True)

    metadata = {
        "positions_m": geometry["positions_m"],
        "directions": geometry["directions"],
        "area_weights_m2": geometry["area_weights_m2"],
        "longitudinal_coordinate": geometry["longitudinal_coordinate"],
        "proximal_distal_coordinate": geometry["proximal_distal_coordinate"],
        "hemisphere_code": geometry["hemisphere_code"],
    }
    metadata_path = subject_forward / "hippunfold-hippocampal-source-metadata.npz"
    np.savez(metadata_path, **metadata)

    generator = np.random.default_rng(7)
    raw_leadfield = generator.normal(size=(FIXTURE_SENSORS, len(geometry["area_weights_m2"])))
    leadfield_path = subject_forward / "hippunfold-hippocampal-fixed-leadfield.npy"
    np.save(leadfield_path, raw_leadfield)

    # The fixture is generated with the frozen implementation, so the audit is
    # checked against an independent reimplementation of the same contract.
    anterior, proximal_distal, _ = oriented_intrinsic_coordinates(
        metadata["positions_m"],
        metadata["longitudinal_coordinate"],
        metadata["proximal_distal_coordinate"],
        metadata["hemisphere_code"],
        metadata["area_weights_m2"],
        endpoint_decile=float(FIXTURE_SUPPORT["endpoint_decile"]),
        minimum_endpoint_separation_m=float(
            FIXTURE_SUPPORT["minimum_endpoint_separation_m"]
        ),
    )
    supports, _ = build_source_supports(
        anterior,
        proximal_distal,
        metadata["hemisphere_code"],
        metadata["area_weights_m2"],
        hemisphere_families=FIXTURE_SUPPORT["hemisphere_families"],
        focal_locations=FIXTURE_SUPPORT["focal_locations"],
        focal_extents=FIXTURE_SUPPORT["focal_extents"],
        include_whole_extent=bool(FIXTURE_SUPPORT["include_whole_extent"]),
    )
    hippocampal = referenced_leadfield(raw_leadfield)
    cortical = generator.normal(size=(FIXTURE_SENSORS, 30))
    cortical_areas = np.linspace(0.5, 1.5, 30)
    cholesky, full_trace, _, _ = standardized_nuisance(
        hippocampal,
        metadata["area_weights_m2"],
        cortical,
        cortical_areas,
        float(config["standardized_noise_fraction"]),
    )

    deterministic_rows: list[dict[str, object]] = []
    for identifier in sorted(supports):
        support = supports[identifier]
        for regime, cycles in _regimes(config):
            phase = deterministic_phase(anterior[support.indices], cycles)
            metrics, _ = phase_locked_metrics(
                hippocampal, support, phase, full_trace, cholesky
            )
            deterministic_rows.append(
                {
                    "subject": FIXTURE_SUBJECT,
                    **_support_fields(support),
                    "regime": regime,
                    "wave_cycles": cycles,
                    **metrics,
                }
            )
    _write_csv(subject_results / "deterministic_conditions.csv", deterministic_rows)

    coherence_rows: list[dict[str, object]] = []
    for identifier in sorted(supports):
        support = supports[identifier]
        for width in config["patch_coherence"]["intrinsic_bin_widths"]:  # type: ignore[index]
            metrics, _ = patch_coherence_metrics(
                hippocampal,
                support,
                anterior,
                proximal_distal,
                metadata["hemisphere_code"],
                float(width),
                full_trace,
                cholesky,
            )
            coherence_rows.append(
                {
                    "subject": FIXTURE_SUBJECT,
                    **_support_fields(support),
                    "intrinsic_bin_width": float(width),
                    **metrics,
                }
            )
    _write_csv(subject_results / "patch_coherence_conditions.csv", coherence_rows)

    random_config = dict(config["random_phase"])  # type: ignore[arg-type]
    random_rows: list[dict[str, object]] = []
    for support_row in FIXTURE_RANDOM_SUPPORTS:
        identifier = support_identifier(
            str(support_row["hemisphere"]),
            str(support_row["location"]),
            float(support_row["extent"]),
        )
        support = supports[identifier]
        local = support.indices
        for length in random_config["intrinsic_correlation_lengths"]:
            for replicate in range(int(random_config["replicates"])):
                phase, phase_report = random_correlated_phases(
                    anterior[local],
                    proximal_distal[local],
                    metadata["hemisphere_code"][local],
                    support.conditional_weights,
                    correlation_length=float(length),
                    features=int(random_config["random_fourier_features"]),
                    phase_standard_deviation_rad=float(
                        random_config["marginal_phase_standard_deviation_rad"]
                    ),
                    master_seed=int(random_config["master_seed"]),
                    seed_components=(FIXTURE_SUBJECT, identifier, float(length), replicate),
                )
                metrics, _ = phase_locked_metrics(
                    hippocampal, support, phase, full_trace, cholesky
                )
                random_rows.append(
                    {
                        "subject": FIXTURE_SUBJECT,
                        **_support_fields(support),
                        "intrinsic_correlation_length": float(length),
                        "replicate": replicate,
                        "phase_seed_manifest_json": json.dumps(
                            phase_report["hemispheres"], sort_keys=True
                        ),
                        **metrics,
                    }
                )
    _write_csv(subject_results / "random_phase_conditions.csv", random_rows)

    tables = {
        "deterministic_conditions.csv": deterministic_rows,
        "patch_coherence_conditions.csv": coherence_rows,
        "random_phase_conditions.csv": random_rows,
    }
    report = {
        "schema_version": 1,
        "ok": True,
        "protocol": PROTOCOL,
        "subject": FIXTURE_SUBJECT,
        "qc": {"synthetic_fixture": True},
        "implementation_sha256": {},
        "inputs": {
            "fixed_leadfield": {
                "path": str(leadfield_path),
                "bytes": leadfield_path.stat().st_size,
                "sha256": _sha256(leadfield_path),
            },
            "metadata": {
                "path": str(metadata_path),
                "bytes": metadata_path.stat().st_size,
                "sha256": _sha256(metadata_path),
            },
        },
        "outputs": {
            name: {
                "bytes": (subject_results / name).stat().st_size,
                "sha256": _sha256(subject_results / name),
                "rows": len(rows),
            }
            for name, rows in tables.items()
        },
    }
    report_path = subject_results / "report.json"
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    (subject_results / ".hippunfold_ensembles.json").write_text(
        json.dumps(
            {
                "status": "complete",
                "subject": FIXTURE_SUBJECT,
                "protocol": PROTOCOL,
                "report_sha256": _sha256(report_path),
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )
    config_path = root / "fixture_config.json"
    config_path.write_text(json.dumps(config, indent=2, sort_keys=True) + "\n")
    return {
        "root": root,
        "config": config_path,
        "forward_root": forward_root,
        "result_root": result_root,
        "report": report_path,
    }


def _run_audit(fixture: dict[str, Path], tag: str) -> tuple[int, dict[str, object], Path]:
    output = fixture["root"] / f"audit_{tag}.json"
    table = fixture["root"] / f"audit_{tag}_subjects.csv"
    completed = subprocess.run(
        [
            sys.executable,
            str(AUDIT_SCRIPT),
            "--config",
            str(fixture["config"]),
            "--forward-root",
            str(fixture["forward_root"]),
            "--result-root",
            str(fixture["result_root"]),
            "--status-root",
            str(fixture["root"] / "status"),
            "--subjects",
            FIXTURE_SUBJECT,
            "--output",
            str(output),
            "--subject-table",
            str(table),
        ],
        cwd=str(PROJECT_ROOT),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    payload = json.loads(output.read_text(encoding="utf-8"))
    return completed.returncode, payload, table


def _rewrite_report_hashes(fixture: dict[str, Path]) -> None:
    report_path = fixture["report"]
    report = json.loads(report_path.read_text(encoding="utf-8"))
    subject_results = report_path.parent
    for name in report["outputs"]:
        path = subject_results / name
        report["outputs"][name] = {
            "bytes": path.stat().st_size,
            "rows": sum(1 for _ in path.open("r", encoding="utf-8")) - 1,
            "sha256": _sha256(path),
        }
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    (subject_results / ".hippunfold_ensembles.json").write_text(
        json.dumps(
            {
                "status": "complete",
                "subject": FIXTURE_SUBJECT,
                "protocol": PROTOCOL,
                "report_sha256": _sha256(report_path),
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def _declare_container_inputs(fixture: dict[str, Path]) -> None:
    """Rewrite a report to declare container-style ``/forward`` input paths.

    The real per-subject reports are written inside the conductor container, so
    their ``inputs[*].path`` values are ``/forward/<subject>/<basename>`` rather
    than a host path.  This helper reproduces that shape on the fixture while
    keeping the declared byte counts and SHA-256 values correct, then refreshes
    the completion marker so the report hash stays consistent.
    """

    report_path = fixture["report"]
    report = json.loads(report_path.read_text(encoding="utf-8"))
    subject = str(report["subject"])
    for metadata in report["inputs"].values():
        basename = Path(str(metadata["path"])).name
        metadata["path"] = f"/forward/{subject}/{basename}"
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    (report_path.parent / ".hippunfold_ensembles.json").write_text(
        json.dumps(
            {
                "status": "complete",
                "subject": FIXTURE_SUBJECT,
                "protocol": PROTOCOL,
                "report_sha256": _sha256(report_path),
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def _corrupt_declared_input_hash(fixture: dict[str, Path], name: str) -> None:
    report_path = fixture["report"]
    report = json.loads(report_path.read_text(encoding="utf-8"))
    metadata = report["inputs"][name]
    metadata["sha256"] = "0" * 64
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    (report_path.parent / ".hippunfold_ensembles.json").write_text(
        json.dumps(
            {
                "status": "complete",
                "subject": FIXTURE_SUBJECT,
                "protocol": PROTOCOL,
                "report_sha256": _sha256(report_path),
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def _clone_fixture(fixture: dict[str, Path], directory: str) -> dict[str, Path]:
    clone = Path(directory) / "clone"
    shutil.copytree(fixture["root"], clone)
    cloned = dict(fixture)
    cloned["root"] = clone
    cloned["config"] = clone / "fixture_config.json"
    cloned["forward_root"] = clone / "forward"
    cloned["result_root"] = clone / "results"
    cloned["report"] = clone / "results" / FIXTURE_SUBJECT / "report.json"
    return cloned


class DeclaredInputResolutionTests(unittest.TestCase):
    def test_container_forward_path_resolves_under_forward_root(self) -> None:
        resolution = resolve_declared_input(
            "123456",
            "/forward/123456/hippunfold-hippocampal-fixed-leadfield.npy",
            Path("derivatives/forward"),
        )
        self.assertTrue(resolution.resolved_from_container)
        self.assertEqual(
            resolution.declared,
            "/forward/123456/hippunfold-hippocampal-fixed-leadfield.npy",
        )
        host = Path(resolution.host_path)
        self.assertEqual(host.name, "hippunfold-hippocampal-fixed-leadfield.npy")
        self.assertEqual(host.parent.name, "123456")
        self.assertEqual(host.parent.parent, Path("derivatives/forward"))

    def test_declared_subject_identity_overrides_container_subject(self) -> None:
        resolution = resolve_declared_input(
            "999999",
            "/forward/123456/hippunfold-hippocampal-source-metadata.npz",
            Path("/mnt/forward"),
        )
        self.assertTrue(resolution.resolved_from_container)
        self.assertEqual(Path(resolution.host_path).parent.name, "999999")
        self.assertEqual(
            Path(resolution.host_path).name,
            "hippunfold-hippocampal-source-metadata.npz",
        )

    def test_host_path_is_used_verbatim(self) -> None:
        declared = str(Path(tempfile.gettempdir()) / "forward" / "123456" / "file.npy")
        resolution = resolve_declared_input("123456", declared, Path("/other"))
        self.assertFalse(resolution.resolved_from_container)
        self.assertEqual(resolution.declared, declared)
        self.assertEqual(str(resolution.host_path), declared)

    def test_container_path_without_file_name_is_excluded(self) -> None:
        with self.assertRaises(AuditError):
            resolve_declared_input("123456", "/forward/123456/", Path("derivatives/forward"))


class NormalizationIdentityTests(unittest.TestCase):
    def setUp(self) -> None:
        self.generator = np.random.default_rng(20260921)

    def test_aligned_identical_columns_reach_unit_ratio(self) -> None:
        columns = np.tile(self.generator.normal(size=(9, 1)), (1, 6))
        areas = self.generator.uniform(0.5, 2.0, size=6)
        z_power, trace, ratio = retained_power(
            columns, areas, np.ones(6, dtype=np.complex128)
        )
        self.assertAlmostEqual(ratio, 1.0, places=14)
        self.assertAlmostEqual(z_power, trace, places=12)

    def test_exact_cancellation_reaches_zero_ratio(self) -> None:
        column = self.generator.normal(size=(9, 1))
        columns = np.column_stack((column, -column))
        _, trace, ratio = retained_power(
            columns, np.array([1.0, 1.0]), np.ones(2, dtype=np.complex128)
        )
        self.assertGreater(trace, 0.0)
        self.assertLessEqual(abs(ratio), 1e-15)

    def test_leadfield_scale_invariance(self) -> None:
        columns = self.generator.normal(size=(8, 5))
        phase = unit_phase_from_angles(self.generator.uniform(0, 2 * math.pi, 5))
        areas = self.generator.uniform(0.4, 3.0, size=5)
        _, trace, ratio = retained_power(columns, areas, phase)
        scaled_z, scaled_trace, scaled_ratio = retained_power(
            12.0 * columns, areas, phase
        )
        self.assertAlmostEqual(ratio, scaled_ratio, places=14)
        self.assertAlmostEqual(scaled_trace, 144.0 * trace, places=10)
        full_trace = float(
            np.dot(np.full(5, 0.2), np.sum(columns * columns, axis=0))
        )
        self.assertAlmostEqual(
            whole_sheet_power(scaled_z, 0.4, 144.0 * full_trace),
            whole_sheet_power(trace * ratio, 0.4, full_trace),
            places=13,
        )

    def test_uniform_raw_area_scale_invariance(self) -> None:
        columns = self.generator.normal(size=(8, 5))
        phase = unit_phase_from_angles(self.generator.uniform(0, 2 * math.pi, 5))
        areas = self.generator.uniform(0.4, 3.0, size=5)
        base_z, base_trace, base_ratio = retained_power(columns, areas, phase)
        scaled_z, scaled_trace, scaled_ratio = retained_power(
            columns, 6.5 * areas, phase
        )
        self.assertAlmostEqual(base_ratio, scaled_ratio, places=14)
        self.assertAlmostEqual(base_trace, scaled_trace, places=12)
        self.assertAlmostEqual(base_z, scaled_z, places=12)

    def test_mesh_split_of_identical_columns(self) -> None:
        columns = self.generator.normal(size=(8, 4))
        phase = unit_phase_from_angles(self.generator.uniform(0, 2 * math.pi, 4))
        areas = np.array([0.5, 1.5, 0.75, 0.25])
        base_z, base_trace, base_ratio = retained_power(columns, areas, phase)
        split_columns = np.column_stack(
            (columns[:, 0][:, None], columns[:, 0][:, None], columns[:, 1:])
        )
        split_areas = np.array([0.25, 0.25, 1.5, 0.75, 0.25])
        split_phase = np.concatenate(([phase[0], phase[0]], phase[1:]))
        split_z, split_trace, split_ratio = retained_power(
            split_columns, split_areas, split_phase
        )
        self.assertAlmostEqual(base_ratio, split_ratio, places=14)
        self.assertAlmostEqual(base_trace, split_trace, places=12)
        self.assertAlmostEqual(base_z, split_z, places=12)

    def test_weighted_jensen_bound_and_extremes(self) -> None:
        columns = np.tile(self.generator.normal(size=(10, 1)), (1, 4))
        areas = self.generator.uniform(0.2, 4.0, size=4)
        self.assertAlmostEqual(
            retained_power(columns, areas, np.ones(4, dtype=np.complex128))[2],
            1.0,
            places=14,
        )
        for _ in range(32):
            random_columns = self.generator.normal(size=(10, 7))
            random_phase = unit_phase_from_angles(
                self.generator.uniform(0, 2 * math.pi, 7)
            )
            random_areas = self.generator.uniform(0.1, 5.0, size=7)
            ratio = retained_power(random_columns, random_areas, random_phase)[2]
            self.assertGreaterEqual(ratio, 0.0)
            self.assertLessEqual(ratio, 1.0 + 1e-12)

    def test_independent_phase_expectation_differs_from_reference(self) -> None:
        columns = self.generator.normal(size=(6, 7))
        areas = np.array([0.40, 0.24, 0.14, 0.10, 0.06, 0.04, 0.02])
        analytic = independent_phase_power(columns, areas)
        trials = 200000
        phase = unit_phase_from_angles(
            self.generator.uniform(0.0, 2.0 * math.pi, size=(trials, 7))
        )
        quadrature = phase * (areas / np.sum(areas))[None, :]
        field = quadrature @ columns.T
        monte_carlo = float(np.mean(np.sum(field * field.conjugate(), axis=1).real))
        self.assertLess(abs(monte_carlo - analytic) / analytic, 0.01)
        _, incoherent, _ = retained_power(
            columns, areas, np.ones(7, dtype=np.complex128)
        )
        self.assertGreater(abs(analytic - incoherent) / incoherent, 0.1)

    def test_uniform_conditional_weights_give_reference_over_n(self) -> None:
        columns = self.generator.normal(size=(6, 9))
        counts = (2, 5, 9)
        for count in counts:
            areas = np.ones(count, dtype=np.float64)
            expectation = independent_phase_power(columns[:, :count], areas)
            _, reference, _ = retained_power(
                columns[:, :count], areas, np.ones(count, dtype=np.complex128)
            )
            self.assertAlmostEqual(expectation, reference / count, places=14)
            self.assertLess(expectation, reference)
            self.assertAlmostEqual(expectation / reference, 1.0 / count, places=14)
        # Corroborate the 1/N factor by Monte Carlo at one uniform N > 1.
        count = 5
        areas = np.ones(count, dtype=np.float64)
        _, reference, _ = retained_power(
            columns[:, :count], areas, np.ones(count, dtype=np.complex128)
        )
        trials = 200000
        phase = unit_phase_from_angles(
            self.generator.uniform(0.0, 2.0 * math.pi, size=(trials, count))
        )
        field = (phase * (areas / np.sum(areas))[None, :]) @ columns[:, :count].T
        monte_carlo = float(np.mean(np.sum(field * field.conjugate(), axis=1).real))
        self.assertLess(abs(monte_carlo - reference / count) / (reference / count), 0.01)

    def test_whole_sheet_scaling_with_area_fraction(self) -> None:
        columns = self.generator.normal(size=(8, 5))
        phase = unit_phase_from_angles(self.generator.uniform(0, 2 * math.pi, 5))
        areas = self.generator.uniform(0.4, 3.0, size=5)
        z_power, trace, ratio = retained_power(columns, areas, phase)
        full_trace = float(
            np.dot(np.full(5, 0.2), np.sum(columns * columns, axis=0))
        )
        fraction = 0.25
        direct = whole_sheet_power(z_power, fraction, full_trace)
        composed = fraction**2 * ratio * trace / full_trace
        self.assertAlmostEqual(direct, composed, places=14)
        self.assertAlmostEqual(
            whole_sheet_power(z_power, 2.0 * fraction, full_trace), 4.0 * direct, places=13
        )

    def test_module_identity_suite_passes(self) -> None:
        records = synthetic_identity_checks()
        self.assertTrue(synthetic_checks_passed(records))
        self.assertEqual(len(records), 9)


class MalformedInputTests(unittest.TestCase):
    def setUp(self) -> None:
        self.columns = np.arange(12, dtype=np.float64).reshape(4, 3) + 1.0
        self.phase = np.ones(3, dtype=np.complex128)

    def test_nonpositive_area_is_excluded(self) -> None:
        with self.assertRaises(AuditError):
            retained_power(self.columns, np.array([1.0, 0.0, 1.0]), self.phase)
        with self.assertRaises(AuditError):
            support_weights(np.array([1.0, -0.5, 2.0]), np.array([0, 1]))

    def test_empty_support_is_excluded(self) -> None:
        with self.assertRaises(AuditError):
            support_weights(np.array([1.0, 2.0]), np.array([], dtype=np.int64))

    def test_non_unit_phase_is_excluded(self) -> None:
        with self.assertRaises(AuditError):
            retained_power(self.columns, np.ones(3), np.array([1.0, 2.0, 1.0]))
        with self.assertRaises(AuditError):
            retained_power(self.columns, np.ones(3), np.array([0.0, 0.0, 0.0]))

    def test_misaligned_shapes_are_excluded(self) -> None:
        with self.assertRaises(AuditError):
            retained_power(self.columns, np.ones(2), self.phase)
        with self.assertRaises(AuditError):
            retained_power(self.columns, np.ones(3), np.ones(2, dtype=np.complex128))

    def test_non_finite_inputs_are_excluded(self) -> None:
        broken = self.columns.copy()
        broken[0, 0] = np.nan
        with self.assertRaises(AuditError):
            retained_power(broken, np.ones(3), self.phase)
        with self.assertRaises(AuditError):
            unit_phase_from_angles(np.array([0.0, np.nan]))

    def test_zero_denominator_is_excluded(self) -> None:
        with self.assertRaises(AuditError):
            retained_power(np.zeros((4, 3)), np.ones(3), self.phase)

    def test_whole_sheet_arguments_are_validated(self) -> None:
        with self.assertRaises(AuditError):
            whole_sheet_power(1.0, 0.0, 1.0)
        with self.assertRaises(AuditError):
            whole_sheet_power(1.0, 1.5, 1.0)
        with self.assertRaises(AuditError):
            whole_sheet_power(1.0, 0.5, 0.0)

    def test_patch_bin_width_is_validated(self) -> None:
        with self.assertRaises(AuditError):
            coherent_patch_index(
                np.array([0.0, 0.5]), np.array([0.0, 0.5]), np.array([-1, -1]), 0.0
            )
        with self.assertRaises(AuditError):
            coherent_patch_index(
                np.array([0.0, 1.5]), np.array([0.0, 0.5]), np.array([-1, -1]), 0.5
            )

    def test_missing_metadata_arrays_are_excluded(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "metadata.npz"
            np.savez(path, positions_m=np.zeros((2, 3)))
            with self.assertRaises(AuditError):
                load_metadata(path)
            self.assertRaises(AuditError, load_metadata, Path(directory) / "absent.npz")

    def test_negative_metadata_areas_are_excluded(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "metadata.npz"
            count = 4
            np.savez(
                path,
                positions_m=np.zeros((count, 3)),
                directions=np.tile(np.array([0.0, 0.0, 1.0]), (count, 1)),
                area_weights_m2=np.array([1.0, -1.0, 1.0, 1.0]),
                longitudinal_coordinate=np.linspace(0.0, 1.0, count),
                proximal_distal_coordinate=np.zeros(count),
                hemisphere_code=np.array([-1, -1, 1, 1], dtype=np.int8),
            )
            with self.assertRaises(AuditError):
                load_metadata(path)

    def test_misaligned_leadfield_shape_is_excluded(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "leadfield.npy"
            np.save(path, np.zeros((5, 3)))
            with self.assertRaises(AuditError):
                load_fixed_leadfield(path, 5, 4)
            with self.assertRaises(AuditError):
                load_fixed_leadfield(Path(directory) / "absent.npy", 5, 4)


class AuditFixtureTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls._temporary = tempfile.mkdtemp(prefix="retained_power_audit_")
        cls.fixture = generate_fixture(Path(cls._temporary))

    @classmethod
    def tearDownClass(cls) -> None:
        shutil.rmtree(cls._temporary, ignore_errors=True)

    def test_audit_accepts_faithful_fixture(self) -> None:
        returncode, payload, table = _run_audit(self.fixture, "clean")
        self.assertEqual(
            returncode,
            0,
            msg=f"audit failed: {payload.get('errors')}",
        )
        self.assertTrue(payload["ok"])
        self.assertEqual(payload["counts"]["subjects_audited"], 1)
        self.assertEqual(payload["counts"]["audited_rows"]["deterministic"], 195)
        self.assertEqual(payload["counts"]["audited_rows"]["patch_coherence"], 195)
        self.assertEqual(
            payload["counts"]["audited_rows"]["random_phase"],
            6 * 4 * FIXTURE_RANDOM_REPLICATES,
        )
        self.assertLessEqual(payload["maximum_relative_error"], 1e-9)
        self.assertTrue(payload["identity_outcomes"]["passed"])
        resolution = payload["declared_input_resolution"][FIXTURE_SUBJECT]
        for name in ("fixed_leadfield", "metadata"):
            entry = resolution[name]
            self.assertFalse(entry["resolved_from_container"])
            self.assertTrue(entry["matches"])
        addendum = payload["normalization_addendum"]
        self.assertEqual(addendum["path"], ADDENDUM)
        self.assertTrue(addendum["present"])
        self.assertFalse(addendum["part_of_frozen_implementation_manifest"])
        self.assertNotIn(addendum["path"], payload["implementation_hashes"])
        with table.open("r", encoding="utf-8", newline="") as stream:
            rows = list(csv.DictReader(stream))
        self.assertEqual(len(rows), 1)
        self.assertEqual(rows[0]["status"], "passed")

    def test_audit_resolves_container_declared_inputs(self) -> None:
        with tempfile.TemporaryDirectory(prefix="retained_power_container_") as directory:
            fixture = _clone_fixture(self.fixture, directory)
            _declare_container_inputs(fixture)
            returncode, payload, _ = _run_audit(fixture, "container")
            self.assertEqual(returncode, 0, msg=payload.get("errors"))
            self.assertTrue(payload["ok"])
            resolution = payload["declared_input_resolution"][FIXTURE_SUBJECT]
            for name in ("fixed_leadfield", "metadata"):
                entry = resolution[name]
                self.assertTrue(
                    entry["resolved_from_container"],
                    msg=f"{name} was not resolved from a container path",
                )
                self.assertTrue(entry["present"])
                self.assertTrue(entry["matches"], msg=f"{name} hash mismatch")
                declared = str(entry["declared_path"])
                self.assertTrue(declared.startswith("/forward/"))
                host = Path(entry["resolved_host_path"])
                self.assertTrue(host.is_file())
                self.assertEqual(host.parent.name, FIXTURE_SUBJECT)
                self.assertEqual(host.name, Path(declared).name)
                self.assertEqual(
                    host.parent.parent, Path(fixture["forward_root"])
                )

    def test_audit_rejects_tampered_container_input_hash(self) -> None:
        with tempfile.TemporaryDirectory(prefix="retained_power_badinput_") as directory:
            fixture = _clone_fixture(self.fixture, directory)
            _declare_container_inputs(fixture)
            _corrupt_declared_input_hash(fixture, "metadata")
            returncode, payload, _ = _run_audit(fixture, "container_tampered")
            self.assertEqual(returncode, 2)
            self.assertFalse(payload["ok"])
            self.assertTrue(
                any("declared input hash mismatch" in message for message in payload["errors"]),
                msg=payload["errors"],
            )

    def test_audit_rejects_missing_container_input(self) -> None:
        with tempfile.TemporaryDirectory(prefix="retained_power_absentinput_") as directory:
            fixture = _clone_fixture(self.fixture, directory)
            _declare_container_inputs(fixture)
            (
                Path(fixture["forward_root"])
                / FIXTURE_SUBJECT
                / "hippunfold-hippocampal-source-metadata.npz"
            ).unlink()
            returncode, payload, _ = _run_audit(fixture, "container_missing")
            self.assertEqual(returncode, 2)
            self.assertFalse(payload["ok"])

    def test_audit_rejects_tampered_value(self) -> None:
        with tempfile.TemporaryDirectory(prefix="retained_power_tamper_") as directory:
            clone = Path(directory) / "clone"
            shutil.copytree(self.fixture["root"], clone)
            fixture = dict(self.fixture)
            fixture["root"] = clone
            fixture["result_root"] = clone / "results"
            fixture["report"] = clone / "results" / FIXTURE_SUBJECT / "report.json"
            table_path = clone / "results" / FIXTURE_SUBJECT / "deterministic_conditions.csv"
            with table_path.open("r", encoding="utf-8", newline="") as stream:
                rows = list(csv.DictReader(stream))
            rows[0]["support_normalized_retained_power_ratio"] = str(
                float(rows[0]["support_normalized_retained_power_ratio"]) * 1.0001
            )
            _write_csv(table_path, rows)
            _rewrite_report_hashes(fixture)
            returncode, payload, _ = _run_audit(fixture, "tampered")
            self.assertEqual(returncode, 2)
            self.assertFalse(payload["ok"])
            self.assertTrue(
                any("recomputed" in message for message in payload["errors"]),
                msg=payload["errors"],
            )

    def test_audit_rejects_missing_rows(self) -> None:
        with tempfile.TemporaryDirectory(prefix="retained_power_missing_") as directory:
            clone = Path(directory) / "clone"
            shutil.copytree(self.fixture["root"], clone)
            fixture = dict(self.fixture)
            fixture["root"] = clone
            fixture["result_root"] = clone / "results"
            fixture["report"] = clone / "results" / FIXTURE_SUBJECT / "report.json"
            table_path = clone / "results" / FIXTURE_SUBJECT / "patch_coherence_conditions.csv"
            with table_path.open("r", encoding="utf-8", newline="") as stream:
                rows = list(csv.DictReader(stream))
            _write_csv(table_path, rows[:-1])
            _rewrite_report_hashes(fixture)
            returncode, payload, _ = _run_audit(fixture, "missing_row")
            self.assertEqual(returncode, 2)
            self.assertFalse(payload["ok"])

    def test_audit_rejects_missing_table(self) -> None:
        with tempfile.TemporaryDirectory(prefix="retained_power_absent_") as directory:
            clone = Path(directory) / "clone"
            shutil.copytree(self.fixture["root"], clone)
            fixture = dict(self.fixture)
            fixture["root"] = clone
            fixture["result_root"] = clone / "results"
            fixture["report"] = clone / "results" / FIXTURE_SUBJECT / "report.json"
            (clone / "results" / FIXTURE_SUBJECT / "random_phase_conditions.csv").unlink()
            returncode, payload, _ = _run_audit(fixture, "absent_table")
            self.assertEqual(returncode, 2)
            self.assertFalse(payload["ok"])

    def test_audit_cli_help_is_usable(self) -> None:
        completed = subprocess.run(
            [sys.executable, str(AUDIT_SCRIPT), "--help"],
            cwd=str(PROJECT_ROOT),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        self.assertEqual(completed.returncode, 0)
        self.assertIn("--subject-table", completed.stdout)
        self.assertIn("--forward-root", completed.stdout)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="optional path for a JSON summary; nothing is written when omitted",
    )
    args = parser.parse_args()
    suite = unittest.TestSuite(
        [
            unittest.defaultTestLoader.loadTestsFromTestCase(loader)
            for loader in (
                NormalizationIdentityTests,
                MalformedInputTests,
                AuditFixtureTests,
            )
        ]
    )
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    summary = {
        "schema_version": 1,
        "protocol": PROTOCOL,
        "checked_at_utc": datetime.now(timezone.utc).isoformat(),
        "tests_run": result.testsRun,
        "failures": len(result.failures),
        "errors": len(result.errors),
        "successful": result.wasSuccessful(),
    }
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    raise SystemExit(main())
